### ISSUE TITLE
useMemo does not guarantee value will not be recreated

### ISSUE THREAD

**Issue by cdomigan** [carloslfu/use-machine#10]
From the React Hooks docs:

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

I think a ref would be more suitable for holding the machine instance - `useMemo` could break this hook in future!

**Comment by cdomigan** [comment]
A ref is where you should store the service. You will want to follow the lazy instantiation example for `useRef` from https://reactjs.org/docs/hooks-faq.html#how-to-create-expensive-objects-lazily

eg

```
const serviceRef = useRef(null);

// ✅ Service is created lazily once
function getService() {
  let service = serviceRef.current;
  if (service !== null) {
    return service;
  }
  let newService = interpret(machine);
  serviceRef.current = newService;
  return newService;
}

// When you need it, call getService()
```

**Comment by carloslfu** [comment]
You're right, thanks @cdomigan.

**Comment by carloslfu** [comment]
I fixed it in another branch, code here https://github.com/carloslfu/use-machine/blob/fix-use-memo/src/index.ts#L37, what do you think @cdomigan?

**Comment by carloslfu** [comment]
It's merged now, I'm gonna test it before release.

**Comment by carloslfu** [comment]
Released in https://github.com/carloslfu/use-machine/tree/v1.1.0.
