### ISSUE TITLE
It doesn't transition to other state 

### ISSUE THREAD

**Issue by aislanmaia** [carloslfu/use-machine#15]
As `xstate 4.3.3` and using `use-machine 1.1.0`, the state doesn't get transitioned to others states at all. 
Just tested with the following [tutorial](https://css-tricks.com/finite-state-machines-with-react/) (updating it to use use-machine and just plain functions components through React Hooks) and tested with the example in the README of this repo.

It seems just get dispatched and captured the events, but doesn't transitions.

**Comment by carloslfu** [comment]
Hi, @aislanmaia. Thanks for reporting. Did you resolve it? If not please provide a code example or a sandbox (in codesandbox.com) and, I´ll review it.

**Comment by aislanmaia** [comment]
Hello @carloslfu. Thanks for replying. I don't know what happened, maybe I misunderstood some concepts, but I checked that the statechart was something locked into just 2 states chains, and the others wasn't get triggered. Anyways I have resolved it. But now, I'm getting confused because I'm losing my state through the hot-reloads from `create-react-app`. 

My question is how can I use the `use-machine` states to survive the reloads after saving. Maybe I should open another issue to this question?? I have uploaded a repo with the reproducible issue.
Here: [example project](it remote add origin https://github.com/aislanmaia/cra-xstate-use-machines-example.git)

**Comment by carloslfu** [comment]
You can do it this [way](https://github.com/facebook/create-react-app/issues/93#issuecomment-282359099) easily if you have only one instance of the statechart, if not it becomes trickier but not impossible. You have to create a wrapper around `useMachine` for saving each XState instance and swapping it on hot-reload. I'm gonna create an issue for creating such wrapper.

**Comment by aislanmaia** [comment]
Confirmed working like a charm following the instructions in the link above.

For others in this thread, my `index.js` starting from [example project](https://github.com/aislanmaia/cra-xstate-use-machines-example.git) is as below:

```
/* code above omitted */

const render = (Component) => ReactDOM.render(
  <AppProvider>
    <App />
   </AppProvider>
   , document.getElementById("root")
);

render(App)

if (module.hot) {
  module.hot.accept('./App', () => {
    const NextApp = require('./App').default
    render(NextApp)
  })
}
```
