### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by carloslfu** [carloslfu/use-machine#2]
The tests should be done using Jest and the [React Testing Library](https://github.com/kentcdodds/react-testing-library).

**Comment by kolohelios** [comment]
Created PR to add to add tests. Reported coverage is 100% though we should also be testing initial context. I honored the original style and patterns to the best of my abilities.

Please let me know if you'd like me to send a follow up PR that includes Travis-CI and Coveralls support.

#9

**Comment by carloslfu** [comment]
Great! Thanks, I'll take a look asap.

**Comment by carloslfu** [comment]
I agree on using `Lodash.get` to guard the objects inside `expect`. We can add it as a dev dependency, so there's no problem with it. I already merged #9 so it can be done in other PR.

**Comment by kolohelios** [comment]
You got it. #12 is ready
