### ISSUE TITLE
Naming of 'exState' variable

### ISSUE THREAD

**Issue by craigglennie** [carloslfu/use-machine#3]
Hi, thanks for writing this library, it seems like a nice way to use xstate with React. 

I'm curious about the `exState` variable, which is returned by `useMachine`. It looks like it's an alias for `machine.state.context`. Is there any reason to use `exState` rather than `machine.state.context`, and if not then what's the rationale for returning it from `useMachine`, versus having the user access `machine.state.context` directly? I get that the latter is more verbose, but from my perspective `exState` was a bit mysterious, and I had to look at the source code to figure out what it was.

The naming is a bit confusing, too - I initially read "ex" as in "previous", but it's just occurred to me that it might be "exState" as in "xState" but with the "e" added to avoid confusing the variable with the library. I guess there are a lot of uses of "state" in play here - "xstate", `useState`, `machine.state`... but maybe there's a better name than `exState`? I'd propose `machineState`, though I think `machineContext` would also work, since if you're using `xstate` then you're going to be familiar with its concept of context - not to be confused with React context, of course!

**Comment by carloslfu** [comment]
Hi @craigglennie.`exState` stands for the external state but you are right it is confusing. Thanks for your feedback. I'll rename it to context asap.

**Comment by carloslfu** [comment]
Fixed in 79dd49e97535d63d9f58726a81add3cc4703afd0.
