### ISSUE TITLE
Optional options / context?

### ISSUE THREAD

**Issue by dakom** [carloslfu/use-machine#6]
At a glance it seems like these can be provided in the MachineConfig itself, no?

**Comment by dakom** [comment]
i.e. is it possible to have a version that's just `useMachine({config})` or `useMachineSimple(config)` ?

**Comment by dakom** [comment]
Sorry - I'll clarify a bit more:

I see that actions must be passed separately, but they are not required

Also, initial context can be set in the config itself.

So I suggest wrapping the arguments to `useMachine` in an object, with only `config` required, and then only using `options` and `initialContext` if they are provided

**Comment by carloslfu** [comment]
Hey @dakom. I think it's a good idea. It'll be a breaking change.

**Comment by dakom** [comment]
Didn't realize that this is following the same API as `Machine` (just opened an issue on xstate, referenced above)

I do think it's better that the API's match so I'd suggest waiting to see what happens on xstate itself before making this breaking change

**Comment by carloslfu** [comment]
Closing because of https://github.com/davidkpiano/xstate/issues/314#issuecomment-456558823.
