### ISSUE TITLE
State updates from the useState() and useReducer() Hooks don't support the second callback argument

### ISSUE THREAD

**Issue by aikidoshi** [carloslfu/use-machine#8]
This issue started since the react upgrade to 16.8.1.
The full text is:
State updates from the useState() and useReducer() Hooks don't support the second callback argument. To execute a side effect after rendering, declare it in the component body with useEffect().
Regards,
aikidoshi

**Comment by carloslfu** [comment]
Thanks @aikidoshi. Now fixed in [v1.0.2](https://github.com/carloslfu/use-machine/tree/v1.0.2).
